### ISSUE TITLE
trouble with optional paradigm block

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-separable#15]
From [apertium-eng-kir.eng-kir.lsx](https://github.com/apertium/apertium-eng-kir/blob/master/apertium-eng-kir.eng-kir.lsx)
```
		<e lm="make really hot" c="ысыт">
			<p>
				<l>make<s n="vblex"/></l>
				<r>make<b/>hot<s n="vblex"/></r>
			</p>
			<i><t/><j/></i>
			<par n="SN"/>
			<par n="SAdv"/>
			<p>
				<l>hot<s n="adj"/><s n="sint"/><j/></l>
				<r></r>
			</p>
		</e>
```

This rule doesn't apply, apparently (tested, confirmed) because of the shorter version of the rule, without `SAdv`.

In theory, though, there should be an easy way to specify "optional `SAdv`", so these can be condensed into one rule.  Defining such as below does not solve this—it matches the simple rule but not any of the versions with adverbs.

```
		<pardef n="optSAdv">
			<e></e>
			<e><par n="adv"/></e>
			<e><par n="adv"/><par n="adv"/></e>
		</pardef>
```

A sentence that can be tested is "Бул тон мени (аябай) ысытып атат" with expected output of "This fur coat is making me (really) hot."

**Comment by mr-martian** [comment]
I believe this is the same issue is as #18, namely that `lsx-proc` was not LRLM until a few days ago. The example given above now works for me.
