### ISSUE TITLE
Problems with a match

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-separable#2]
In apertium-fra-cat we have the file apertium-fra-cat.cat-fra.l2x

There are several rules which are more or less a copy-and-paste but none of them has been tested.

I've tried with the rule "rendre public", which is supposed to split the multiword "rendre# public" if it is followed by "pas" changing "rendre public pas" into "rendre pas public". Unfortunately it doesn't work:
```
> no faig públic.
> ^no/no<adv>$ ^faig públic/fer<vblex><pri><p1><sg># públic$^./.<sent>$ 
> ^no/no<adv>$ ^faig públic/fer# públic<vblex><pri><p1><sg>$^./.<sent>$ 
> ^no<adv>$ ^fer# públic<vblex><pri><p1><sg>$^.<sent>$ 
> ^no<adv>/ne<adv>/non<adv>$ ^fer# públic<vblex><pri><p1><sg>/rendre# public<vblex><pri><p1><sg>$^.<sent>/.<sent>$ 
> ^no<adv>/ne<adv>$ ^fer# públic<vblex><pri><p1><sg>/rendre# public<vblex><pri><p1><sg>$^.<sent>/.<sent>$ 
> ^ne<adv>$ ^rendre<vblex><pri><p1><sg># public$ ^pas<adv>$^.<sent>$ 
> ~ne rends public pas~. 
> ne rends public pas. 
```
I've tried several possibilities of matching, but I couldn't make the rule work (there are two rules now, just as a try: there is no match).

Any help would be appreciated.

**Comment by ftyers** [comment]
@irene-tang @jonorthwash  any ideas, I thought this was already fixed?

**Comment by jonorthwash** [comment]
I think more info is needed to understand what's going on. Could you share the rule you're expecting to work, the command you're using to compile it, input *at that stage only*, and actual and expected output?

**Comment by hectoralos** [comment]
You are right, @jonorthwash.

The input is:

`^ne<adv>$ ^rendre<vblex><pri><p1><sg># public$ ^pas<adv>$ `

The expected output is:

`^ne<adv>$ ^rendre<vblex><pri><p1><sg>$ ^pas<adv>$ ^public<n><m><sg>$`

The original rule is:
```
    <e lm="rendre public" c="">
      <p><l>rendre<g><b/>public</g><s n="vblex"/></l><r>rendre<s n="vblex"/></r></p>
      <i><t/><j/></i>
      <p><l></l><r>pas<s n="adv"/><j/></r></p>
      <p><l></l><r>public<s n="n"/><s n="m"/><s n="sg"/><j/></r></p>
      <p><l>pas<s n="adv"/><j/></l><r></r></p>
    </e>
```
I have try different other possibilities. The last one was:
```
    <e lm="rendre public" c="">
      <p><l>rendre<s n="vblex"/><t/><g><b/>public</g><j/></l><r>rendre<s n="vblex"/><t/><j/></r></p>
      <p><l></l><r>pas<s n="adv"/><j/></r></p>
      <p><l></l><r>public<s n="n"/><s n="m"/><s n="sg"/><j/></r></p>
      <p><l>pas<s n="adv"/><j/></l><r></r></p>
    </e>
```

**Comment by jonorthwash** [comment]
@hectoralos, and how did you compile the transducer?

**Comment by hectoralos** [comment]
@jonorthwash, I am not sure if I understand your question. I've done this, maybe it is want you are asking for:
```
> touch apertium-fra-cat.cat-fra.l2x
> make
lsx-comp rl apertium-fra-cat.cat-fra.l2x cat-fra.autosep.bin
main@standard 230 246
```

**Comment by hectoralos** [comment]
Great, @xavivars ! It's working now. And I better understand how the module works. Thank you very much!
