### ISSUE TITLE
Issue with capital letters

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-separable#21]
This works:
```xml

        <e lm="Jun Ajpu" c=""><p>
                <l>jun<s n="num"/><j/>ajpu<s n="np"/><s n="ant"/><s n="m"/><j/></l>
                <r>Jun<b/>Ajpu<s n="np"/><s n="ant"/><s n="m"/></r>
            </p>
        </e>
```

```
$ echo "^Jun<num>$ ^Ajpu<np><ant><m>$ " | lsx-proc quc-spa.autoseq.bin 
^Jun Ajpu<np><ant><m>$ 
```

But this doesn't:
```xml

        <e lm="Jun Ajpu" c=""><p>
                <l>Jun<s n="num"/><j/>Ajpu<s n="np"/><s n="ant"/><s n="m"/><j/></l>
                <r>Jun<b/>Ajpu<s n="np"/><s n="ant"/><s n="m"/></r>
            </p>
        </e>
```

```
$ echo "^Jun<num>$ ^Ajpu<np><ant><m>$ " | lsx-proc quc-spa.autoseq.bin 
^Jun<num>$ ^Ajpu<np><ant><m>$ 
```

**Comment by ftyers** [comment]
This looks like it's an issue in `lttoolbox/fst_processor.cc`:
```cpp
        else if(val > 0)
        {
          int val_lowercase = towlower(val);
          s.step_override(val_lowercase, alphabet(L"<ANY_CHAR>"), val); // FIXME deal with cases! in step_override
        }
```

**Comment by mr-martian** [comment]
Oops, I noted how to fix this issue and Github proceeded to close it.

**Comment by mr-martian** [comment]
If https://github.com/apertium/lttoolbox/pull/100 gets merged then in this
https://github.com/apertium/apertium-separable/blob/0818c6dbcdc67e81da2887bf5d4ff9dca4997f75/src/lsx_processor.cc#L235-L241
we just need to change `s.step_override(val, any_char, lu[i]);` to `s.step_override(lu[i], val, any_char, lu[i]);` and it should work, I think.

**Comment by mr-martian** [comment]
@ftyers as of a641a6b, your example works (in fact it's the test case) though now it won't match `^jun<num>$ ^ajpu<np><ant><m>$` (lowercase) - do you foresee that being a problem?

**Comment by mr-martian** [comment]
Closing this, since the behavior is now consistent with `lt-proc`.
