### ISSUE TITLE
Out of sync with lttoolbox

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-separable#4]
Separable no longer builds because of the lttoolbox API changes: https://apertium.projectjj.com/apt/logs/apertium-separable/sid-amd64.log - lots of functions expect an additional parameter.

@Techievena, are the new parameters defaultable to 0? And if so, lttoolbox could be adjusted to make them actually defaultable with `= 0` and thus -separable wouldn't need any code changes. If not, what values are expected now?

**Comment by Techievena** [comment]
@TinoDidriksen https://github.com/apertium/lttoolbox/pull/25 is ready to merge.
