### ISSUE TITLE
lsx-comp compiling error

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-separable#45]
When recompiling the apertium-separable rules for fra-frp, which were working are untouched in the last year, I get an error:
```
$ make
lsx-comp lr apertium-fra-frp.fra-frp.l1x fra-frp.autosep1.bin
lsx-comp: symbol lookup error: lsx-comp: undefined symbol: _ZN8Alphabet5writeEP8_IO_FILE
make: *** [Makefile:819: fra-frp.autosep1.bin] Error 127
```

**Comment by TinoDidriksen** [comment]
Same as https://github.com/apertium/apertium/issues/158 - I forgot more things depended on lttoolbox's ABI.

**Comment by hectoralos** [comment]
I'd be great if this could be solved. We are trying to release oci-fra very soon, and we are blocked here. @mr-martian ?

**Comment by TinoDidriksen** [comment]
This was solved 20 minutes after my comment, and remains solved. I just forgot to close the issue.

**Comment by hectoralos** [comment]
Great! Thanks. I try to get it too soon, and didn't try again because the issue wasn't close.
