### ISSUE TITLE
lsx-comp not running as before

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-separable#46]
When fra-frp was released, as [said in the documentation](https://wiki.apertium.org/wiki/Hectoralos/GSOC_2020_rapport_final#La_synth.C3.A8se_et_la_d.C3.A9composition_de_locutions) , sentences like `j’ai toujours besoin`, `je n’ai pas besoin` or `je n’ai pas toujours besoin`, were translated as `j’é tojorn fôta`, `j’é pas fôta`, `j’é pas tojorn fôta`. This was done thanks to this rule in `apertium-fra-frp.fra-frp.l1x`:
```
    <e lm="avoir besoin">
      <p><l>avoir<s n="vblex"/></l><r>avoir<g><b/>besoin</g><s n="vblex"/></r></p>
      <i><t/><j/></i>
      <par n="adv"/>
      <p><l>besoin<s n="n"/><s n="m"/><t/><j/></l><r></r></p>
    </e>
```
Currently, this rule (and seemingly no rule) in `apertium-fra-frp.fra-frp.l1x` is being matched:
```
$ echo "je n'ai pas besoin" | apertium -d . fra-frp-lsx1
^je<prn><tn><p1><mf><sg>$ ^ne<adv>$ ^avoir<vblex><pri><p1><sg>$ ^pas<adv>$ ^besoin<n><m><sg>$^.<sent>$

$ echo "je n'ai pas besoin" | apertium -d . fra-frp
j'é pas besouen
```
This is also happening in [apertium.org](https://apertium.org/index.fra.html#?dir=fra-frp&q=je%20n%27ai%20pas%20besoin).

**Comment by unhammer** [comment]
I think `<j/>` here should be `<d/>`, there was a change https://github.com/apertium/apertium-separable/issues/42 (but I thought that shouldn't affect already compiled releases?)

**Comment by mr-martian** [comment]
As of #44, `<j/>` is `+` as in monodix and `<d/>` is end-of-word.

I now realize 2 mistakes in the rollout of this change:

1. As usual, I made no announcement of the change outside github issues
2. When updating, I forgot to check for files with extensions other than `.lsx`

I will fix fra-cat and fra-frp in a moment. If there are any other pairs that use an extension besides `.l1x`, the fix is to search-and-replace `<j` with `<d` or feel free to ping me about it.

**Comment by mr-martian** [comment]
On further inspection, no, that rule was updated in https://github.com/apertium/apertium-fra-frp/commit/a26f077e33e1591ac5d54aa71f7892f2f927e3e8#diff-4da21ffcb1896a3b3b7671f79276674867b7a3c330068ba97fc9b272a4e18d94L61

@hectoralos, do you maybe not have the most recent commit to fra-frp?

**Comment by hectoralos** [comment]
No, I didn't. I didn't expect any change. It's working now in my computer.
We really have a very serious problem about communication and documentation.
