### ISSUE TITLE
README is blank

### ISSUE THREAD

**Issue by dolphingarlic** [apertium/apertium-separable#5]
There is nothing in the README

**Comment by unhammer** [comment]
Would you like to write one? Turning http://wiki.apertium.org/wiki/Apertium-separable into a README.md (then symlink README to README.md or the other way around) sounds like an easy enough solution :)

**Comment by TinoDidriksen** [comment]
README should be the real file, and README.md a symlink to README.

**Comment by krashish8** [comment]
@unhammer @TinoDidriksen Is this issue still open? I would like to work on this.

**Comment by TinoDidriksen** [comment]
The `README` file points to the wiki. If you want it to do more than that, feel free to do so. In my opinion the wiki is sufficient, but one could argue documentation should be with the source.

**Comment by krashish8** [comment]
If the `README` file points to the wiki, then I also consider it to be sufficient.

**Comment by nishantwrp** [comment]
Fixed the broken links
