### ISSUE TITLE
Does not work unless <j/> manually added at end of every line

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-separable#9]
@ftyers reports that `lsx-proc` doesn't parse correctly unless `<j/>` is added to the end of every entry.  See #6 for discussion of this issue.

Three possible solutions appear to exist:
- The compiler could add `<j/>` automatically to the end of every entry.
- The parser could assume `<j/>` at the end of every entry.
- Users could be made aware of this [somewhat arbitrary?] requirement.  The documentation would need to be updated.

**Comment by jonorthwash** [comment]
Are we sure that we will never want to be able to match something partial?

**Comment by jonorthwash** [comment]
Also, will existing lsx code need to be cleaned up?

**Comment by mr-martian** [comment]
Anything that was valid will remain valid and anything what would have matched will continue to match.

If you want to match something partial, you'll have to change the lsx section of `lttoolbox/fst_processor.cc`.

**Comment by jonorthwash** [comment]
> Also, will existing lsx code need to be cleaned up?

... Does it need to be, or will it still work if `<j/>` is manually added?

**Comment by mr-martian** [comment]
Existing code is still valid.
